
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_reddit_clone_development
  
  username: postgres
  password: qd!/][Km92

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost

production:
  <<: *default
  database: rails_reddit_clone_production
  username: rails_reddit_clone
  password: <%= ENV["RAILS_REDDIT_CLONE_DATABASE_PASSWORD"] %>
